name: 'Go Publishr'
description: 'Github Action that allows you to push commits, publish artifacts, generate a changelog & create a release'
inputs:
  author_name:
    description: 'Commit Author'
    required: true
    default: 'packagrio-bot'
  author_email:
    description: 'Commit Author Email'
    required: true
    default: 'packagr-io[bot]@users.noreply.github.com'
  upload_assets:
    description: 'Assets to upload'
    required: false
  cwd:
    description: 'Working Directory'
    required: false
    default: ''
outputs:
  version: # id of output
    description: 'Version that was written to files'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PACKAGR_ENGINE_GIT_AUTHOR_NAME: ${{ inputs.author_name }}
    PACKAGR_ENGINE_GIT_AUTHOR_EMAIL: ${{ inputs.author_email }}
    PACKAGR_SCM_RELEASE_ASSETS: ${{ inputs.upload_assets }}
branding:
  icon: 'package'
  color: 'red'
